### PR TITLE
Add support for multiple models of Apple remote + long press

### PR DESCRIPTION
**Pull request by zas**

### CODE REVIEW

**Comment by zas** [comment]
@dspverden I improved the thing a bit so it speeds up when maintaining a long press on volume remote buttons, and tried to debounce very short presses, so it's possible to fine tune volume level. On short presses, it goes with 0.5db as it was before, but when maintaining buttons it speeds up to 1db then 2db.
Tell me what you think once you tested it.

**Comment by zas** [comment]
I'm not yet happy with this code. I'll update the PR once I have something good enough.

**Comment by zas** [comment]
I reworked the code, it is much simpler now, and should work as expected.

**Comment by exislow** [comment]
Great job. Just tested it. Works like charm. Even the logic regarding short long presses and longer long presses. Love it.

**Comment by dspverden** [comment]
To make things a bit more complicated, I had a bunch of Apple remotes here, they all showed different patterns. But it can be narrowed down to a scheme. In hex code the second byte identifies the key while byte 4 & 3 are always 0x77E1xxxx. That means masking byte 2 by 0x0000FF00 will give the key code. Here I found two variants for each key, e.g. Play button is either 0x00007A00 or 0x0000FA00.
See my last commit on develop. There I already implemented that. Perhaps you want to adapt long press solution to it?

**Comment by zas** [comment]
@dspverden did you test my code with those remotes ? The 0x00007A00 or 0x0000FA00 should be handled by 0x00007F00 mask

**Comment by zas** [comment]
@dspverden you didn't answer to my comment above, I need to know what wasn't working with the models you own, before reworking this PR.

**Comment by dspverden** [comment]
Please have a look at the one of the latest commits from develop. There you can see, it seems to be bit 7 (most left) of the the second byte. As you described it above.

**Pull request merged**
